<?php

namespace AppBundle\Repository;

/**
 * GradosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradosRepository extends \Doctrine\ORM\EntityRepository
{
}
